#!/bin/bash

# NOTE: Just pass Jack environment variables to this script (or export in
# calling environment) to specify which server to use.
# You have to boot a server manually before running this

source common.sh

export PYTHONPATH="$(dirname $0):$PYTHONPATH"

client_name=midi_proc_jack_pass_test

fifo_name=/tmp/test_fifo

mkfifo -ma=rw ${fifo_name}_output ${fifo_name}_input

# start sequencer

jack_midiseq Sequencer 24000 0 60 8000 12000 63 8000&

# start fluidsynth

fluidsynth -i -s -a jack -m jack /usr/share/sounds/sf2/FluidR3_GM.sf2&

sleep 1

python3 midi_proc_pass.py $fifo_name &

sleep 1

#gdb --args ./midi_proc_jack $client_name $fifo_name
./midi_proc_jack $client_name $fifo_name&

sleep 1

jack_connect Sequencer:out ${client_name}:input
jack_connect ${client_name}:out fluidsynth:midi
jack_connect fluidsynth:l_00 system:playback_1
jack_connect fluidsynth:r_00 system:playback_2

while [ 1 ]; do
    sleep 1
done

#rm ${fifo_name}_output ${fifo_name}_input
